runtime: php55
env: flex
api_version: 1

handlers:
- url: /.*
  script: main.php

#env_variables:
#  MYSQL_DSN: mysql:unix_socket=/cloudsql/35.188.87.193;dbname=iou
#  MYSQL_USER: root
#  MYSQL_PASSWORD: password
