runtime: php55
api_version: 1

handlers:
- url: /.*
  script: main.php

env_variables:
  # Replace project, instance, database, user and password with the values obtained
  # when configuring your Cloud SQL instance.
  MYSQL_DSN: mysql:unix_socket=/cloudsql/payment-calculator:us-central1:iou-db;dbname=iou-db
  MYSQL_USER: root
  MYSQL_PASSWORD: 'password'
